import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-home-page',
  templateUrl: './home-page.component.html',
  styleUrls: ['./home-page.component.css'],
})
export class HomePageComponent implements OnInit {
  constructor(private router: Router) {}

  ngOnInit(): void {}

  onClick(companyCode: any) {
    console.log(companyCode);

    this.router.navigate(['/company', companyCode]);
  }

  routerList = [
    {
      routeURL: '1111',
      routeName: 'Yahoo Finance Api ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '1140', routeName: 'AL Bilad ', routeDesc: 'bla bla bla' },
    { routeURL: '4300', routeName: 'Dar Al ', routeDesc: 'bla bla bla' },
    { routeURL: '8250', routeName: 'AXA ', routeDesc: 'bla bla bla' },
    { routeURL: '8150', routeName: 'ACIG ', routeDesc: 'bla bla bla' },
    { routeURL: '2090', routeName: 'Gypsum ', routeDesc: 'bla bla bla' },
    { routeURL: '4020', routeName: 'Real Estate', routeDesc: 'bla bla bla' },
    { routeURL: '8300', routeName: 'Wataniya ', routeDesc: 'bla bla bla' },
    { routeURL: '3040', routeName: 'Qassim Cement ', routeDesc: 'bla bla bla' },
    { routeURL: '4220', routeName: 'Emaar E ', routeDesc: 'bla bla bla' },
    {
      routeURL: '8012',
      routeName: 'Jazira Takaful ',
      routeDesc: 'bla bla bla',
    },
    {
      routeURL: '6080',
      routeName: 'Bishah Agriculture ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '8010', routeName: 'Tawuniya ', routeDesc: 'bla bla bla' },
    { routeURL: '6004', routeName: 'Catering ', routeDesc: 'bla bla bla' },
    { routeURL: '2320', routeName: 'AL Babtain ', routeDesc: 'bla bla bla' },
    { routeURL: '6002', routeName: 'Herfy Foods ', routeDesc: 'bla bla bla' },
    { routeURL: '8090', routeName: 'SANAD ', routeDesc: 'bla bla bla' },
    { routeURL: '7050', routeName: 'Almutakamela ', routeDesc: 'bla bla bla' },
    { routeURL: '4140', routeName: 'Saudi Export ', routeDesc: 'bla bla bla' },
    { routeURL: '2150', routeName: 'Glass ', routeDesc: 'bla bla bla' },
    { routeURL: '8210', routeName: 'Bupa Arabia ', routeDesc: 'bla bla bla' },
    {
      routeURL: '2240',
      routeName: 'Zamil Industrial ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2010', routeName: 'SABIC ', routeDesc: 'bla bla bla' },
    {
      routeURL: '8220',
      routeName: 'Weqaya Takaful ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '1090', routeName: 'SAMBA ', routeDesc: 'bla bla bla' },
    { routeURL: '1310', routeName: 'MMG ', routeDesc: 'bla bla bla' },
    { routeURL: '8140', routeName: 'Al ', routeDesc: 'bla bla bla' },
    { routeURL: '1150', routeName: 'Alinma ', routeDesc: 'bla bla bla' },
    { routeURL: '4030', routeName: 'Bahri ', routeDesc: 'bla bla bla' },
    {
      routeURL: '7040',
      routeName: 'Atheeb Telecom ',
      routeDesc: 'bla bla bla',
    },
    {
      routeURL: '6090',
      routeName: 'Jazan Development ',
      routeDesc: 'bla bla bla',
    },
    {
      routeURL: '8020',
      routeName: 'Malath Insurance ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '4230', routeName: 'Red Sea ', routeDesc: 'bla bla bla' },
    { routeURL: '6010', routeName: 'NADEC ', routeDesc: 'bla bla bla' },
    { routeURL: '8290', routeName: 'Solidarity ', routeDesc: 'bla bla bla' },
    { routeURL: '4130', routeName: 'Al Baha ', routeDesc: 'bla bla bla' },
    { routeURL: '1060', routeName: 'SABB ', routeDesc: 'bla bla bla' },
    { routeURL: '3030', routeName: 'Saudi Cement ', routeDesc: 'bla bla bla' },
    { routeURL: '2310', routeName: 'Sipchem ', routeDesc: 'bla bla bla' },
    { routeURL: '2140', routeName: 'Al Ahsa ', routeDesc: 'bla bla bla' },
    {
      routeURL: '2060',
      routeName: 'Industrialization ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2250', routeName: 'SIIG ', routeDesc: 'bla bla bla' },
    { routeURL: '1320', routeName: 'SSP ', routeDesc: 'bla bla bla' },
    { routeURL: '8230', routeName: 'Al Rajhi ', routeDesc: 'bla bla bla' },
    { routeURL: '8030', routeName: 'MEDGULF ', routeDesc: 'bla bla bla' },
    { routeURL: '1080', routeName: 'Arab National ', routeDesc: 'bla bla bla' },
    { routeURL: '1120', routeName: 'Al Rajhi ', routeDesc: 'bla bla bla' },
    { routeURL: '4070', routeName: 'Tihama ', routeDesc: 'bla bla bla' },
    { routeURL: '7030', routeName: 'ZAIN KSA ', routeDesc: 'bla bla bla' },
    { routeURL: '4090', routeName: 'Taiba ', routeDesc: 'bla bla bla' },
    { routeURL: '4200', routeName: 'Aldrees ', routeDesc: 'bla bla bla' },
    { routeURL: '8130', routeName: 'ATC ', routeDesc: 'bla bla bla' },
    { routeURL: '4280', routeName: 'Kingdom ', routeDesc: 'bla bla bla' },
    { routeURL: '4040', routeName: 'SAPTCO ', routeDesc: 'bla bla bla' },
    { routeURL: '2300', routeName: 'SPM ', routeDesc: 'bla bla bla' },
    { routeURL: '3020', routeName: 'Yamamah Cement', routeDesc: 'bla bla bla' },
    { routeURL: '2380', routeName: 'Petro Rabigh ', routeDesc: 'bla bla bla' },
    { routeURL: '2170', routeName: 'Alujain ', routeDesc: 'bla bla bla' },
    { routeURL: '6060', routeName: 'Sharqiya Dev ', routeDesc: 'bla bla bla' },
    {
      routeURL: '2260',
      routeName: 'Sahara Petrochemical ',
      routeDesc: 'bla bla bla',
    },
    {
      routeURL: '2070',
      routeName: 'Pharmaceutical ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '1010', routeName: 'RIBL ', routeDesc: 'bla bla bla' },
    { routeURL: '8040', routeName: 'ALLIANZ SF ', routeDesc: 'bla bla bla' },
    { routeURL: '4210', routeName: 'SRMG ', routeDesc: 'bla bla bla' },
    { routeURL: '2280', routeName: 'Almarai ', routeDesc: 'bla bla bla' },
    { routeURL: '4270', routeName: 'SPPC ', routeDesc: 'bla bla bla' },
    { routeURL: '1330', routeName: 'ALKHODARI ', routeDesc: 'bla bla bla' },
    { routeURL: '4190', routeName: 'Jarir ', routeDesc: 'bla bla bla' },
    {
      routeURL: '7020',
      routeName: 'Etihad Etisalat ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '8200', routeName: 'Saudi Re ', routeDesc: 'bla bla bla' },
    { routeURL: '8280', routeName: 'Al Alamiya ', routeDesc: 'bla bla bla' },
    { routeURL: '8120', routeName: 'Gulf Union ', routeDesc: 'bla bla bla' },
    { routeURL: '2270', routeName: 'SADAFCO ', routeDesc: 'bla bla bla' },
    { routeURL: '2040', routeName: 'Ceramic ', routeDesc: 'bla bla bla' },
    { routeURL: '4050', routeName: 'SASCO ', routeDesc: 'bla bla bla' },
    { routeURL: '3010', routeName: 'Arab Cement ', routeDesc: 'bla bla bla' },
    { routeURL: '6001', routeName: 'H B ', routeDesc: 'bla bla bla' },
    {
      routeURL: '4290',
      routeName: 'Alkhaleej Trng ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '3090', routeName: 'Tabuk Cement ', routeDesc: 'bla bla bla' },
    { routeURL: '3091', routeName: 'Jouf Cement ', routeDesc: 'bla bla bla' },
    {
      routeURL: '6070',
      routeName: 'Jouff Agriculture',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2370', routeName: 'MESC ', routeDesc: 'bla bla bla' },
    { routeURL: '2160', routeName: 'Amiantit ', routeDesc: 'bla bla bla' },
    { routeURL: '4260', routeName: 'Budget Saudi ', routeDesc: 'bla bla bla' },
    { routeURL: '4080', routeName: 'Assir ', routeDesc: 'bla bla bla' },
    { routeURL: '8050', routeName: 'SALAMA ', routeDesc: 'bla bla bla' },
    { routeURL: '4110', routeName: 'Mubarrad ', routeDesc: 'bla bla bla' },
    { routeURL: '4180', routeName: 'Fitaihi Group ', routeDesc: 'bla bla bla' },
    { routeURL: '2290', routeName: 'YANSAB ', routeDesc: 'bla bla bla' },
    { routeURL: '2190', routeName: 'SISCO ', routeDesc: 'bla bla bla' },
    {
      routeURL: '3004',
      routeName: 'Northern Cement ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '3001', routeName: 'HCC ', routeDesc: 'bla bla bla' },
    { routeURL: '3003', routeName: 'City Cement ', routeDesc: 'bla bla bla' },
    { routeURL: '3002', routeName: 'Najran Cement ', routeDesc: 'bla bla bla' },
    {
      routeURL: '8110',
      routeName: 'WAFA Insurance ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '7010', routeName: 'STC ', routeDesc: 'bla bla bla' },
    { routeURL: '2200', routeName: 'Pipes ', routeDesc: 'bla bla bla' },
    { routeURL: '2050', routeName: 'SAVOLA  Group ', routeDesc: 'bla bla bla' },
    { routeURL: '8190', routeName: 'U C ', routeDesc: 'bla bla bla' },
    { routeURL: '4061', routeName: 'Anaam Holding ', routeDesc: 'bla bla bla' },
    { routeURL: '1301', routeName: 'ASLAK ', routeDesc: 'bla bla bla' },
    {
      routeURL: '6040',
      routeName: 'Tabuk Agriculture ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2110', routeName: 'Cables ', routeDesc: 'bla bla bla' },
    {
      routeURL: '1030',
      routeName: 'Saudi Investment ',
      routeDesc: 'bla bla bla',
    },
    {
      routeURL: '3080',
      routeName: 'Eastern Cement ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2360', routeName: 'SVCP ', routeDesc: 'bla bla bla' },
    { routeURL: '1212', routeName: 'Astra Indust ', routeDesc: 'bla bla bla' },
    {
      routeURL: '1213',
      routeName: 'AlSorayai Group',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '1210', routeName: 'BCI ', routeDesc: 'bla bla bla' },
    { routeURL: '1211', routeName: 'MA ', routeDesc: 'bla bla bla' },
    { routeURL: '8100', routeName: 'SAICO ', routeDesc: 'bla bla bla' },
    { routeURL: '1214', routeName: 'SHAKER ', routeDesc: 'bla bla bla' },
    {
      routeURL: '8060',
      routeName: 'Walaa Insurance ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2180', routeName: 'FIPCO ', routeDesc: 'bla bla bla' },
    { routeURL: '8260', routeName: 'Gulf General ', routeDesc: 'bla bla bla' },
    { routeURL: '2210', routeName: 'Nama Chemicals', routeDesc: 'bla bla bla' },
    { routeURL: '4170', routeName: 'Shams', routeDesc: 'bla bla bla' },
    { routeURL: '1020', routeName: 'BJAZ ', routeDesc: 'bla bla bla' },
    {
      routeURL: '8180',
      routeName: 'Sagr Insurance ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2020', routeName: 'SAFCO ', routeDesc: 'bla bla bla' },
    { routeURL: '2350', routeName: 'Saudi Kayan ', routeDesc: 'bla bla bla' },
    { routeURL: '2100', routeName: 'Food ', routeDesc: 'bla bla bla' },
    {
      routeURL: '6050',
      routeName: 'Saudi Fisheries ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '8170', routeName: 'Trade Union ', routeDesc: 'bla bla bla' },
    {
      routeURL: '5110',
      routeName: 'Saudi Electricity ',
      routeDesc: 'bla bla bla',
    },
    {
      routeURL: '8070',
      routeName: 'Arabian Shield ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '1201', routeName: 'Takween ', routeDesc: 'bla bla bla' },
    { routeURL: '4240', routeName: 'AlHokair ', routeDesc: 'bla bla bla' },
    { routeURL: '3060', routeName: 'Yanbu Cement ', routeDesc: 'bla bla bla' },
    { routeURL: '8270', routeName: 'Buruj ', routeDesc: 'bla bla bla' },
    { routeURL: '1050', routeName: 'Saudi Fransi ', routeDesc: 'bla bla bla' },
    { routeURL: '1810', routeName: 'ALTAYYAR ', routeDesc: 'bla bla bla' },
    { routeURL: '2340', routeName: 'AlAbdullatif ', routeDesc: 'bla bla bla' },
    {
      routeURL: '2130',
      routeName: 'Saudi Industrial ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '4160', routeName: 'Thim ', routeDesc: 'bla bla bla' },
    { routeURL: '4001', routeName: 'A ', routeDesc: 'bla bla bla' },
    { routeURL: '4002', routeName: 'Mouwasat ', routeDesc: 'bla bla bla' },
    { routeURL: '4003', routeName: 'Extra ', routeDesc: 'bla bla bla' },
    { routeURL: '4004', routeName: 'Dallah Health ', routeDesc: 'bla bla bla' },
    { routeURL: '4005', routeName: 'Care ', routeDesc: 'bla bla bla' },
    { routeURL: '2220', routeName: 'Maadaniyah ', routeDesc: 'bla bla bla' },
    { routeURL: '2030', routeName: 'SARCO ', routeDesc: 'bla bla bla' },
    {
      routeURL: '6020',
      routeName: 'Qassim Agriculture ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '4310', routeName: 'KEC ', routeDesc: 'bla bla bla' },
    { routeURL: '8160', routeName: 'AICC ', routeDesc: 'bla bla bla' },
    { routeURL: '4250', routeName: 'Jabal Omar ', routeDesc: 'bla bla bla' },
    { routeURL: '4100', routeName: 'Makkah ', routeDesc: 'bla bla bla' },
    {
      routeURL: '8310',
      routeName: 'AMANA Insurance ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '8311', routeName: 'Enaya ', routeDesc: 'bla bla bla' },
    { routeURL: '8312', routeName: 'Alinma Tokio ', routeDesc: 'bla bla bla' },
    { routeURL: '8240', routeName: 'ACE ', routeDesc: 'bla bla bla' },
    {
      routeURL: '3050',
      routeName: 'Southern Cement ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2330', routeName: 'Advanced ', routeDesc: 'bla bla bla' },
    {
      routeURL: '2120',
      routeName: 'Saudi Advanced ',
      routeDesc: 'bla bla bla',
    },
    {
      routeURL: '4150',
      routeName: 'Arriyadh Development ',
      routeDesc: 'bla bla bla',
    },
    {
      routeURL: '1040',
      routeName: 'Saudi Hollandi ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '8080', routeName: 'SABB Takaful ', routeDesc: 'bla bla bla' },
    {
      routeURL: '2230',
      routeName: 'Saudi Chemical ',
      routeDesc: 'bla bla bla',
    },
    { routeURL: '2080', routeName: 'Gas ', routeDesc: 'bla bla bla' },
    { routeURL: '4010', routeName: 'Hotels ', routeDesc: 'bla bla bla' },
    { routeURL: '2002', routeName: 'Petrochem ', routeDesc: 'bla bla bla' },
    { routeURL: '2001', routeName: 'CHEMANOL ', routeDesc: 'bla bla bla' },
  ];
}
